guide = ARGF.readlines.map(&:split)

ROCK_VALUE = 1
PAPER_VALUE = 2
SCISSORS_VALUE = 3

LOSS_POINTS = 0
TIE_POINTS = 3
WIN_POINTS = 6

OPPONENT_ROCK = "A"
OPPONENT_PAPER = "B"
OPPONENT_SCISSORS = "C"

US_ROCK = "X"
US_PAPER = "Y"
US_SCISSORS = "Z"

GUIDE_TO_VALUE_LOOKUP = {
  [OPPONENT_ROCK, US_ROCK] => ROCK_VALUE + TIE_POINTS,
  [OPPONENT_ROCK, US_PAPER] => PAPER_VALUE + WIN_POINTS,
  [OPPONENT_ROCK, US_SCISSORS] => SCISSORS_VALUE + LOSS_POINTS,
  [OPPONENT_PAPER, US_ROCK] => ROCK_VALUE + LOSS_POINTS,
  [OPPONENT_PAPER, US_PAPER] => PAPER_VALUE + TIE_POINTS,
  [OPPONENT_PAPER, US_SCISSORS] => SCISSORS_VALUE + WIN_POINTS,
  [OPPONENT_SCISSORS, US_ROCK] => ROCK_VALUE + WIN_POINTS,
  [OPPONENT_SCISSORS, US_PAPER] => PAPER_VALUE + LOSS_POINTS,
  [OPPONENT_SCISSORS, US_SCISSORS] => SCISSORS_VALUE + TIE_POINTS
}

p guide.sum { |entry| GUIDE_TO_VALUE_LOOKUP[entry] }
